version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CodeDeployDemo/CodeDeployDemo.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -o ./build_output CodeDeployDemo/CodeDeployDemo.csproj
artifacts:
  files:
    - CodeDeployDemo/build_output/**/*
    - scripts/**/*
    - appspec.yml
